---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: all
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    # - verify
    - destroy

platforms:
  - name: apps-wazuh-agent-ubuntu20
    image: lotusnoir/ansible_molecule_test_images:ubuntu20
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    capabilities: ["NET_ADMIN"]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-ubuntu22
    image: lotusnoir/ansible_molecule_test_images:ubuntu22
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-ubuntu24
    image: lotusnoir/ansible_molecule_test_images:ubuntu24
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-debian12
    image: lotusnoir/ansible_molecule_test_images:debian12
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-debian11
    image: lotusnoir/ansible_molecule_test_images:debian11
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-debian10
    image: lotusnoir/ansible_molecule_test_images:debian10
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-debian13
    image: lotusnoir/ansible_molecule_test_images:debian13
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-rocky10
    image: lotusnoir/ansible_molecule_test_images:rocky10
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-rocky8
    image: lotusnoir/ansible_molecule_test_images:rocky8
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-rocky9
    image: lotusnoir/ansible_molecule_test_images:rocky9
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-oraclelinux10
    image: lotusnoir/ansible_molecule_test_images:oraclelinux10
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-oraclelinux8
    image: lotusnoir/ansible_molecule_test_images:oraclelinux8
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-agent-oraclelinux9
    image: lotusnoir/ansible_molecule_test_images:oraclelinux9
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3

provisioner:
  name: ansible
  connection_options:
    ansible_remote_tmp: /tmp
    ansible_python_interpreter: auto_silent
  config_options:
    defaults:
      roles_path: "${HOME}/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:$MOLECULE_PROJECT_DIRECTORY/.."
      callbacks_enabled: timer, profile_tasks, profile_roles
      verbosity: 3
      forks: 20
      host_key_checking: false
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=600s
  log: true
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      bullseye:
        ansible_python_interpreter: "/usr/bin/python3.9"
      bookworm:
        ansible_python_interpreter: "/usr/bin/python3.9"
      trixie:
        ansible_python_interpreter: "/usr/bin/python3.9"

verifier:
  name: ansible
