---
- name: "Debian | Install gnupg"
  ansible.builtin.package:
    name: "gnupg"
    state: present
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success

- name: "Debian | Remove old wazuh apt signing key"
  ansible.builtin.apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    keyring: /etc/apt/trusted.gpg
    state: absent
  when: wazuh_repository is not defined

- name: "Debian | Add wazuh apt signing key"
  ansible.builtin.get_url:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    dest: /etc/apt/trusted.gpg.d/wazuh.asc
    mode: '0644'
    force: true
  when: wazuh_repository is not defined

- name: "Debian | Add wazuh repo to apt list"
  ansible.builtin.apt_repository:
    repo: "deb https://packages.wazuh.com/{{ wazuh_version }}/apt/ stable main"
    state: present
    filename: wazuh
  when: wazuh_repository is not defined

- name: "Debian | Add wazuh repo to apt list"
  ansible.builtin.apt_repository:
    repo: "{{ wazuh_repository }}"
    state: present
    filename: wazuh
  when: wazuh_repository is defined and wazuh_repository|length > 0

- name: "Debian | Uninstall wazuh-agent package"
  ansible.builtin.apt:
    name: "wazuh-agent"
    state: absent
    purge: true
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success
  when: wazuh_agent_reinstall|bool

- name: "Debian | Delete configuration folder"
  ansible.builtin.file:
    path: "/var/ossec"
    state: absent
  when: wazuh_agent_reinstall|bool

- name: "Debian | Download only wazuh-agent package"
  ansible.builtin.command: apt install --download-only wazuh-agent
  changed_when: false
  when: wazuh_agent_dl_only|bool

- name: "Debian | Install wazuh-agent package"
  ansible.builtin.package:
    name: "wazuh-agent"
    state: present
    update_cache: 'yes'
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_ip }}"
    WAZUH_MANAGER_PORT: "{{ wazuh_manager_port }}"
    WAZUH_PROTOCOL: "{{ wazuh_manager_protocol }}"
    WAZUH_REGISTRATION_SERVER: "{{ wazuh_registration_server }}"
    WAZUH_REGISTRATION_PORT: "{{ wazuh_registration_port }}"
    WAZUH_REGISTRATION_PASSWORD: "{{ wazuh_registration_password }}"
    WAZUH_KEEP_ALIVE_INTERVAL: "{{ wazuh_keep_alive_interval }}"
    WAZUH_TIME_RECONNECT: "{{ wazuh_time_reconnect }}"
    WAZUH_REGISTRATION_CA: "{{ wazuh_registration_ca_path }}"
    WAZUH_REGISTRATION_CERTIFICATE: "{{ wazuh_registration_certificate_path }}"
    WAZUH_REGISTRATION_KEY: "{{ wazuh_registration_key_path }}"
    WAZUH_AGENT_NAME: "{{ wazuh_agent_name }}"
    WAZUH_AGENT_GROUP: "{{ wazuh_agent_group }}"
    ENROLLMENT_DELAY: "{{ wazuh_enrollment_delay }}"
  when: not wazuh_agent_dl_only|bool
