---
- name: Prepare
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      register: apt_update
      until: apt_update is succeeded
      retries: 3
      delay: 10
      when: ansible_facts.os_family == 'Debian'

    - name: Start dbus for oraclelinux9
      ansible.builtin.systemd:
        name: dbus
        state: started
        enabled: true
      when: ansible_facts.os_family == 'RedHat' and (ansible_facts.distribution_major_version | int) >= 9
